### ISSUE TITLE
Object versioning

### ISSUE THREAD

**Issue by ahankinson** [OCFL/Use-Cases#11]
A large research library is digitising its Medieval manuscript holdings. They receive a report that a digitised book has a duplicated image for one of the pages, and realise that the photographer took two images of the same page, and none of the missing page. They re-shoot the missing page. The new page is inserted into the digital object, creating a new version of it.

**Comment by ahankinson** [comment]
Title made more generic. Confirmed in-scope since this seems like a core part of what we're trying to do here.

**Comment by awoods** [comment]
Supported since v0.1
