### ISSUE TITLE
Allow past version file retrievals

### ISSUE THREAD

**Issue by ahankinson** [OCFL/Use-Cases#12]
A researcher has cited a URL to an older version of a digital object in a research article. The institution has implemented the Memento standard, allowing the researcher's citation to refer to the previous version of the digital object, instead of the newest version. The OCFL client presents the files representing the previous version of the object on request.

**Comment by ahankinson** [comment]
F2F 2018.09.05: This will require a timestamp within the `inventory.jsonld` and that the timestamps are increasing.

Mapping OCFL objects to URLs for access is out of scope.

**Comment by awoods** [comment]
Supported since v0.1
