### ISSUE TITLE
Version reversion and deletion for Fedora API compatibility

### ISSUE THREAD

**Issue by tomwrobel** [OCFL/Use-Cases#18]
An institution wishes to implement the Fedora4 API using an OCFL file system for file storage. In order to maintain compatibility with the Fedora4 API, it needs to support the following features: reversion of a version, removal of a previous version.

**Comment by ahankinson** [comment]
There are two methods for reversion that could be considered: reversion that deletes subsequent versions, and reversion that keeps subsequent versions intact; the latter being one that uses the latest version metadata as a pointer to the `HEAD` of the digital object, while keeping the files as hidden members of the object.

I would suggest that we don't allow the latter case, and that if there is a need for reversion, it's a strict wiping of the files from subsequent versions. 

In that case, this would be related to #17 .

**Comment by ahankinson** [comment]
F2F 2018.09.05: This is no longer true for Fedora API; reversion to a previous version requires you to create a new one. This is out-of-scope for the OCFL spec.
