### ISSUE TITLE
Support multiple files with same content in one version of an object

### ISSUE THREAD

**Issue by zimeon** [OCFL/Use-Cases#25]
A repository that archives arbitrary content may include versions of objects that include the same content in two or more files. A special case of this is zero size files. While files with the same content may not occur as a result of controlled digitization workflows, it is easy to imagine cases were user supplied repository content (e.g. from an institutional repository, from arXiv.org, or from a disk image) would include multiple files with identical content (and hence identical digest).

**Comment by ahankinson** [comment]
F2F 2018.09.05: Agreed in scope.

**Comment by zimeon** [comment]
Supported since v0.1
