### ISSUE TITLE
Support Merging Objects

### ISSUE THREAD

**Issue by ahankinson** [OCFL/Use-Cases#28]
As a repository manager, I have systems that operate on my objects remotely (e.g., a cloud service workflow engine can be used to transcode my TIFF images to JPEG2000). These changes would be stored as a new version.

However, I would also want to update other copies of this object with the content from the new version.

Thus, we should support merges of OCFL objects, and identify the cases where this might fail. (e.g., two systems having the same version number, but different changes).

**Comment by ahankinson** [comment]
F2F 2018.09.05: Out-of-scope for v1. OCFL objects have their own lives, and no syncing or merging logic is defined in the OCFL spec. This may be covered in v2.

**Comment by zimeon** [comment]
Per 2018-09-05 comment we should reconsider this for v2

**Comment by zimeon** [comment]
Editors' discussion 2023-09-22: Closing as still out of scope. The reconciliation different changes in replicas of object is beyond OCFL scope, and management of replicas in this way would violate ideas of immutability.
