### ISSUE TITLE
Compatibility with direct-attached and NFS-attached disks

### ISSUE THREAD

**Issue by ahankinson** [OCFL/Use-Cases#3]
The OCFL spec should cover the case of users having direct-attached or NFS/CIFS attached disks.

**Comment by zimeon** [comment]
So far, I don't see any difference between direct-attached or NFS/CIFS that would impact the OCFL model. It is perhaps a design principle that we consider only file or object (for S3 type stores) level properties, and not block level properties.

**Comment by ahankinson** [comment]
I think it's the flip-side of #2 -- we need to explicitly state that direct attach or NFS-attach storage is explicitly in-scope.

**Comment by awoods** [comment]
Supported since v0.1
