### ISSUE TITLE
Recording correctly ingested bad data

### ISSUE THREAD

**Issue by zimeon** [OCFL/Use-Cases#30]
A file is included in a version of an OCFL object that is in some way corrupted (maybe a bad PDF or a badly encoded JPEG2000) although its digest is correct in the OCFL record so the OCFL object itself is entirely valid.

**Comment by ahankinson** [comment]
F2F 2018.09.05: The OCFL spec would not prevent recording badly encoded data. Validation tools MAY decide to log this, and the 'bad' file would be corrected by creating a new version with the corrected file.

Recording details of the corrections are out of scope. Prose may be used to record the reason for the intervention in a commit message or log file, but this would be free-form and not specified.
