### ISSUE TITLE
Support validation of all objects under a storage root according to a particular object disposition convention

### ISSUE THREAD

**Issue by zimeon** [OCFL/Use-Cases#31]
Client code should be able to validate that objects under a storage root conform to a particular object disposition convention, and potentially that no other files exist under the storage root. The convention may be a common/shared one (such as pairtree where that path as constructed from the director path corresponds to the OCFL object `id`) or a local convention. A goal of declaring the structure is to help make the storage root self-documenting.

**Comment by awoods** [comment]
support since v0.2
https://github.com/OCFL/spec/commit/5fda2d7ed1b07c3a4138138ae4e1dca7ad89723e
