### ISSUE TITLE
Storing 100TB of content in S3

### ISSUE THREAD

**Issue by awoods** [OCFL/Use-Cases#38]
As an implementer of an OCFL repository, I want to store ~100TB of content, spread across hundreds of thousands of objects, in AWS S3.

Reference: 
- https://github.com/OCFL/spec/issues/522
- https://github.com/OCFL/Use-Cases/issues/2

**Comment by rosy1280** [comment]
And also this would extend support to Google's Cloud Storage option which also uses the Amazon S3 API.  For reference:

* [Extending an Amazon S3 Integration to Google Cloud Storage With the Interop API - DZone Article](https://dzone.com/articles/extending-an-amazon-s3-integration-to-google-cloud#:~:text=Google%20enables%20the%20S3%2Dinteroperability,user%20basis%20for%20each%20project.&text=While%20you're%20in%20the,authorize%20requests%20with%20HMAC%20authentication)
* [Cloud Storage interoperability - Google Documentation](https://cloud.google.com/storage/docs/interoperability)

**Comment by awoods** [comment]
This use case is supported (and implemented). Closing.

**Comment by zimeon** [comment]
See, for example, https://www.youtube.com/watch?v=bcYW6O-IIk0 for details at Harvard
