### ISSUE TITLE
Distributed Storage of objects and components

### ISSUE THREAD

**Issue by rosy1280** [OCFL/Use-Cases#39]
There are a number of use cases that indicate the need to have different parts of an object stored in a variety of places.

**Comment by zimeon** [comment]
This use case would violate the current [completeness](https://ocfl.io/1.1/spec/#completeness) requirement of v1/v1.1.

**Comment by rosy1280** [comment]
1. Peer storage roots that make up a single repository
2. Objects stored across multiple storage roots
3. Objects that contain references to files in other objects
4. Object contains references to external files not in an OCFL environment (and can we add the digest to that file?)

**Comment by rosy1280** [comment]
### Feedback on Use Cases
In advance of version 2 of the OCFL, we are soliciting feedback on use cases. Please feel free to add your thoughts on this use case via the comments.

### Polling on Use Cases
In addition to reviewing comments, we are doing an informal poll for each use case that has been tagged as `Proposed: In Scope` for version 2.  You can contribute to the poll for this use case by reacting to this comment. The following reactions are supported:

| **In favor of the use case** | **Against the use case** | **Neutral on the use case** |
|:----------------------------:|:------------------------:|:---------------------------:|
| 👍🏼                           | 👎🏼                       | 👀                           |

The poll will remain open through the end of February 2024.

**Comment by rosy1280** [comment]
At the time of this comment, the votes tallied to -1.

We are closing this ticket in favor of all the other use cases referenced in this ticket.
