### ISSUE TITLE
Support multiple services logging to an object

### ISSUE THREAD

**Issue by ahankinson** [OCFL/Use-Cases#6]
An institution wishes to implement a comprehensive automated digital preservation auditing system. This system might be composed of several services that provides fixity checks, format validation, and sanity checking on the filesystem layout. These auditing services will maintain a log within the object itself. A separate log for the entire filesystem may also be maintained.

**Comment by ahankinson** [comment]
F2F 2018.09.05: Confirmed support for logging within an object. Maintain silence on the form of the log itself.

**Comment by awoods** [comment]
Supported since v0.1
