### ISSUE TITLE
Object transfer

### ISSUE THREAD

**Issue by ahankinson** [OCFL/Use-Cases#7]
An organization may wish to transfer a digital object to another organization's storage system. This might be the case in distributed newspaper digitisation initiatives, for example, where individual institutions digitise their collections, but then send them to a central library for access and preservation purposes. In this case, existing standards such as BagIt can be used to package and transfer OCFL objects. An OCFL object, including any metadata about object versions, may be transferred within the BagIt data directory.

**Comment by ahankinson** [comment]
Possibly related to #20 ?

**Comment by zimeon** [comment]
I'd some ways I'd say this is not in-scope in the sense that OCFL is a file layout spec. Having said that, #9 says that the set of files for an object contain the complete description and hence, by bundling that up and shipping it off, this use case is met. Do we need an "Supported but not directly in scope" label? (with better wording)

**Comment by ahankinson** [comment]
I had assumed 'supported' == 'in scope' if we can implicitly do it without needing to explicitly state so in the spec. 

Are you thinking that 'in-scope' means that it needs to be tied directly to verbiage in the spec?

**Comment by zimeon** [comment]
Not sure how we should think about this, perhaps a good discussion topic for a call...

**Comment by ahankinson** [comment]
F2F 2018.09.05: As OCFL objects are just files and folders, use of BagIt or similar are possible, but this is not directly within the scope of the spec.
