### ISSUE TITLE
Digital repository software migrations

### ISSUE THREAD

**Issue by ahankinson** [OCFL/Use-Cases#8]
An institution has decided they wish to switch from one IR system to another. The old IR system does not support OCFL, so they write an exporter that translates the digital objects to an OCFL filesystem. Their new IR does understand OCFL, so once the data is exported they configure their IR to point at the OCFL roots. The new IR crawls the OCFL filesystem and indexes the object metadata into a Solr index for faster lookups.

**Comment by ahankinson** [comment]
Related to #9

**Comment by zimeon** [comment]
Agree that this is a core in-scope use case which leads to the requirement #9

**Comment by ahankinson** [comment]
F2F 2018.09.05: A supported use-case but does not directly affect the spec itself.
